# Jenkins Master Certificate Storage (volume only container)
# This image prepares an empty directory where certificates may be stored

FROM biz/jenkinsuser
MAINTAINER Dominik Ebert <doe@zuehlke.com>

ARG CERT_DIR=/var/certs/localDockerDaemon

VOLUME ${CERT_DIR}

CMD ["true"]
