FROM dci/jenkins
MAINTAINER Dominik Ebert <doe@zuelhke.com>

# Jenkins home directoy is a volume, so configuration and build history 
# can be persisted and survive image upgrades
VOLUME /var/jenkins_home

CMD ["true"]
