node {
    def img

    stage('Clone repository') {
        git branch: 'master', url: 'https://github.com/Zuehlke/BiZEPS.git'
    }

    stage ('Build Jenkins Slave image') {
        docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
            img = docker.build("biz/jenkinsslave:latest", "./buildServer/jenkins/slave")
        }
    }

    stage ('Build MCMA Tools image') {
        docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
            img = docker.build("biz/mcmatools:latest", "./buildTools/mcmatools")
        }
    }

    stage ('Build GCC image') {
        docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
            img = docker.build("biz/gcclatest:latest", "./buildTools/gcclatest")
        }
    }
	
   
    stage ('Build BOOST image') {
        docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
            img = docker.build("biz/gccboostlatest:latest", "./buildTools/gccboostlatest")
        }
    }

    stage ('Run BOOST test') {
        docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
            docker.image("biz/gccboostlatest:latest").inside{
				git branch: 'master', url: 'https://github.com/Zuehlke/BiZEPS.git'
				sh 'cd buildToolsTest/gccboostlatest && make -f makefile all && make -f makefile runtest && make -f makefile clean'
			}
        }
    }
}