node {
    def img

    stage('Clone repository') {
        git branch: 'master', url: 'https://github.com/Zuehlke/BiZEPS.git'
    }
    
    stage ('Build Jenkins Master') {
        docker.withServer(${DEFAULT_DOCKER_HOST_CONNECTION}, 'default-docker-host-credentials') {
            img = docker.build("bizeps/jenkins:latest", "./buildServer/jenkins/master")
        }
    }
}