node {

  docker.withServer("${DEFAULT_DOCKER_HOST_CONNECTION}", 'default-docker-host-credentials') {
  
    def imgJenkins
  
    stage('Clone Repository') {
      git branch: 'master', url: 'https://github.com/Zuehlke/BiZEPS.git'
    }
    
    stage ('Build Images') {
      imgJenkins = docker.build("bizeps/jenkins:latest", "./buildServer/jenkins/master")
    }
    
    stage ('Push Images') {
        imgJenkins.push();
    }
  }
}